global.DefaultLang = "zh-CN"
global.SiteName = "None"
global.RegisterPath = "https://127/register.php"
global.CartPath = "https://127/cart.php"
global.APIPath = "https://127/modules/servers/V2raySocks/api.php"
global.ucKey = "123"
global.licKey = "123"